FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy source code
COPY . .

# Environment
ENV NODE_ENV=production
ENV PORT=5050
EXPOSE 5050

# Start server
CMD ["node", "server.js"]